import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/pages/Import.module.scss'
import { HeaderSmall } from '../components/headerSmall'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import { Form } from '../components/form'

const Import: NextPage = () => {

  const router = useRouter();

  const [ route, setRoute ] = useState(true)

  useEffect(() => {
    if (router.asPath === '/') {
      setRoute(true)
    } else if (router.asPath === '/list') {
      setRoute(false)
    }
  }, [router])

  return (
    <div className={styles.container}>
      <Head>
        <title>Import</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <HeaderSmall route={route}/>
        <div className={styles.import}>
          <h1>Transação</h1>
          <Form />

        </div>
        
      </main>
    </div>
  )
}

export default Import
